#!/bin/bash
cmake ../../../ \
-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
-DCMAKE_BUILD_TYPE=Release \
-DANDROID_ABI="armeabi-v7a" \
-DANDROID_STL=c++_static \
-DCMAKE_BUILD_TYPE=Release \
-DANDROID_NATIVE_API_LEVEL=android-14  \
-DANDROID_TOOLCHAIN=clang \
-DMNN_USE_LOGCAT=true \
-DMNN_USE_SSE=OFF \
-DMNN_NPU:BOOL=true \
-DMNN_VULKAN:BOOL=ON \
-DMNN_OPENCL:BOOL=ON \
#-DMNN_OPENMP:BOOL=ON \
#-DMNN_OPENGL:BOOL=ON \
#-DMNN_SUPPORT_BF16=OFF \
#-DMNN_DEBUG:BOOL=ON \
#-DMNN_BUILD_BENCHMARK:BOOL=ON \
-DMNN_BUILD_TEST=ON \
-DMNN_BUILD_FOR_ANDROID_COMMAND=true \
-DNATIVE_LIBRARY_OUTPUT=. -DNATIVE_INCLUDE_OUTPUT=. $1 $2 $3

make -j4
